### ISSUE TITLE
function type is missing 

### ISSUE THREAD

**Issue by sandeepkumaar** [JoshuaWise/tiny-schema#1]
Hi @JoshuaWise, 
very nice library !

function type is missing in the package 

## Expected
```
let bool = is('function')((i) => i) // true
```
## Actual
```
let bool = is('function')((i) => i) // throws 'Malformed schema string'
```

Let me know if you would be interested in a PR. Thanks.

**Comment by JoshuaWise** [comment]
@sandeepkumaar, thank you for the kind words!

Adding a `function` type would be out-of-scope for this package since it's only designed to validate JSON data, not all the types found in JavaScript. You're welcome to fork it to expand the scope to all JavaScript types!

**Comment by sandeepkumaar** [comment]
Make sense! closing the issue :+1:
